/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import org.jsoup.Jsoup;
import javax.swing.JTextArea;
import com.google.gson.*;
//import com.google.gson.JsonArray;
//import com.google.gson.JsonObject;
//import com.google.gson.JsonParser;
import java.io.IOException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;

/**
 *
 * @author kostas
 */
public class NewJFrame extends javax.swing.JFrame {

    private Object jList;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("projectPU");
    EntityManager em = emf.createEntityManager();
    SearchKeyJpaController controllerM = new SearchKeyJpaController(emf);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(880, 600));

        jLabel1.setText("Εγκυκλοπαίδεια:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Αναζήτηση");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton3.setText("Επιλογή");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton3)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    String keyword = jTextField1.getText().trim();
    
    //Έλεγχος αν ο χρήστης έχει βάλει λέξη στην αναζήτηση
    if (keyword.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Παρακαλώ δώστε μια λέξη!");
        return; 
    }
    
    
    SearchKey searchKey = controllerM.findSearchKey(keyword);
    
    try{
        if (searchKey == null){
            SearchKey key = new SearchKey(keyword, 1);
            controllerM.create(key);
        }else{
            searchKey.addSearch();
            controllerM.edit(searchKey);
        }
    }
    catch(Exception e){
        e.getMessage();
    }

    //  Προετοιμασία OkHttpClient
    okhttp3.OkHttpClient client = new okhttp3.OkHttpClient();
    
    try {
        // Σωστό Encoding για τα Ελληνικά
        //String encodedSearch = java.net.URLEncoder.encode(keyword, java.nio.charset.StandardCharsets.UTF_8.toString());
        String url = "https://el.wikipedia.org/w/api.php?action=query&list=search&srsearch="+ keyword +"&format=json" ;

        //  Κατασκευή του Request
        okhttp3.Request request = new okhttp3.Request.Builder()
                .url(url)
                .header("User-Agent", "WikiViewer/1.0 (student-project@eap.gr)")
                .build();

        //  Εκτέλεση της κλήσης
       try (okhttp3.Response response = client.newCall(request).execute()) {
        if (response.isSuccessful() && response.body() != null) {
            String responseString = response.body().string();
            System.out.println(responseString);
            
            
            //com.google.gson.JsonObject rootObject = new com.google.gson.JsonParser().parse(responseString).getAsJsonObject();
    
            GsonBuilder builder = new GsonBuilder();
            builder.setPrettyPrinting();
            Gson gson = builder.create();
            
            JsonObject jsonObject = gson.fromJson(responseString, JsonObject.class);
            
            JsonObject queryObject = jsonObject.getAsJsonObject("query");
            
            JsonArray jsonArray = queryObject.getAsJsonArray("search");
            //JsonArray jsonArray = gson.fromJson(responseString, JsonArray.class);
            
            if (jsonArray.size() == 0){
                JOptionPane.showMessageDialog(null, "Δεν βρέθηκαν αποτελέσματα","ενημέρωση", JOptionPane.WARNING_MESSAGE );
                
            }
           //DefaultListModel listModel = new DefaultListModel<>();
            
            
        DefaultListModel<Article> listModel = new DefaultListModel<>(); // Ορίζουμε ότι η λίστα έχει Articles

        for (int i = 0; i < jsonArray.size(); i++) {
            JsonObject result = jsonArray.get(i).getAsJsonObject();
    
    // Δημιουργία αντικειμένου με τον default constructor
            Article art = new Article(); 
    
    // Γέμισμα του αντικειμένου από το JSON
            art.setTitle(result.get("title").getAsString());
            art.setPageid(result.get("pageid").getAsInt());
            art.setTimestamp(result.get("timestamp").getAsString());
            
            //Καθαρισμός κειμένου
            String snippet = (result.get("snippet").getAsString());
            
            String cleanSnippet = snippet.replaceAll("<[^>]*>", "")
                                .replace("&quot;", "\"")
                                .replace("&amp;", "&");
            art.setSnippet(cleanSnippet);
    // Προσθήκη ολόκληρου του αντικειμένου στο μοντέλο
            listModel.addElement(art); 
}
        
 
            jList1.setModel(listModel);
        }
    }
} catch (Exception e) {
    e.getMessage();
}




    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
   
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       
    // Λήψη των δεδομένων από τα πεδία
    //String title = jTextField4.getText();
    //String pageId = jTextField2.getText();
   // String timestamp = jTextField3.getText();
   // String snippet = jTextArea1.getText();

    // Έλεγχος αν υπάρχουν δεδομένα
    //if (title.isEmpty() || pageId.isEmpty() || timestamp.isEmpty()) {
    //    JOptionPane.showMessageDialog(this, "Δεν έχει επιλεγεί άρθρο!", "Προσοχή", JOptionPane.WARNING_MESSAGE);
   //     return;
   // }
    
    Article selectedArt = (Article) jList1.getSelectedValue();
   
    
    if (selectedArt == null) {
        JOptionPane.showMessageDialog(this, "Παρακαλώ επιλέξτε ένα άρθρο από τη λίστα!");
        return;
    }
    
    
    SaveFrame saveFrame = new SaveFrame(
        selectedArt.getTitle(), 
        selectedArt.getTimestamp(), 
        String.valueOf(selectedArt.getPageid()), 
        selectedArt.getSnippet(),
        selectedArt.getComments()
    );
    // Άνοιγμα του SaveFrame με τα δεδομένα
    //SaveFrame saveFrame = new SaveFrame(title, timestamp, pageId, snippet);
    saveFrame.setLocationRelativeTo(null);
    saveFrame.setVisible(true);

        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<Article> jList1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    
       
    
}
