/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.log.Logger;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.lang.System.Logger.Level;
import java.util.Comparator;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.table.DefaultTableModel;
import javax.persistence.Query;
import javax.swing.JOptionPane;
/**
 *
 * @author kostas
 */
public class statisticsFrame extends javax.swing.JFrame {

    
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("projectPU");
    EntityManager em = emf.createEntityManager();
    ArticleJpaController controllerK = new ArticleJpaController(emf);
    CategoryJpaController controllerL = new CategoryJpaController(emf);
    SearchKeyJpaController controllerM = new SearchKeyJpaController(emf);
    /**
     * Creates new form statisticsFrame
     */
    public statisticsFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Προβολή στατιστικών και εκτύπωση σε PDF");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ΛΕΞΕΙΣ-ΚΛΕΙΔΙΑ", "ΑΝΑΖΗΤΗΣΕΙΣ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ΚΑΤΗΓΟΡΙΑ", "ΠΛΗΘΟΣ ΑΡΘΡΩΝ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("Προβολή");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("PDF");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Δημιουργούμε TableMOdel για τον πίνακα
        DefaultTableModel model = new DefaultTableModel();
        //Ορίζουμε τις επικεφαλίδες στον πίνακα
        model.setColumnIdentifiers(new String[]{"ΛΕΞΕΙΣ-ΚΛΕΙΔΙΑ", "ΑΝΑΖΗΤΗΣΕΙΣ"});
        
        
        //Τα στατιστικά αυτά πρέπει να μπορούν να προβληθούν ύπο την μορφή πίνακα
        List<SearchKey> searchKeys = controllerM.findSearchKeyEntities();
        searchKeys.sort(Comparator.comparing(SearchKey::getSearchCount).reversed());
        
        for (SearchKey keys : searchKeys){
            String search = String.valueOf(keys.getSearchCount());
            
            //Πίνακας για τις προβολές
            String[] row = new String[]{keys.getKeyword(), search};
            
            //Προσθέτω στον πίνακα τις γραμμές
            model.addRow(row);
            }
        
        //Ενημερώνω τον πίνακα
        jTable1.setModel(model);
        
        
        Query q = em.createQuery(
                    " SELECT a.category.id, COUNT(a)"
                + " FROM Article a  "
                + "GROUP BY a.category.id "
                + "ORDER BY COUNT (a) DESC");
        
        //Δημιουργούμε TableModel για τον πίνακα
        List<Object[]> results = q.getResultList();
        DefaultTableModel model2 = new DefaultTableModel();
        
        //Ορίζουμε τις επικεφαλίδες του πίνακα
        model2.setColumnIdentifiers(new String[]{"ΚΑΤΗΓΟΡΙΑ", "ΠΛΗΘΟΣ ΑΡΘΡΩΝ"});
        
        for (Object[] row : results){
            model2.addRow(row);
        }
        jTable2.setModel(model2);
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jTable1.getValueAt(1, 0) != null){
            //Δημιουργώ ένα αντικείμενο doc
            Document doc = new Document(PageSize.A4);
           
            try {
                //Το όνομα του αρχείου που δημιουργώ
                PdfWriter.getInstance(doc, new FileOutputStream("stats.pdf"));
                //Άνοιγμα doc
                doc.open();
                
                //Δημιουργία PdfTable ΛΕΞΕΙΣ-ΚΛΕΙΔΙΑ
                PdfPTable pdfTable = new PdfPTable(jTable1.getColumnCount());
                
                //Ορισμός ελληνικών χαρακτήρων
                BaseFont arialGreek = BaseFont.createFont("C:\\Windows\\Fonts\\arial.ttf",
                        BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
                
                Font arial = new Font(arialGreek, 12);
                Font arial18 = new Font(arialGreek, 18, Font.BOLD);
                
                //Παίρνω την επικεφαλίδα απο το jTable και την προσθέτο στο pdfTable
                for(int i = 0; i < jTable1.getColumnCount(); i++){
                    PdfPCell cell = new PdfPCell(new Paragraph(jTable1.getColumnName(i), arial));
                    pdfTable.addCell(cell);
                }
                
                for (int rows = 0; rows < jTable1.getRowCount(); rows++){
                    for(int columns = 0; columns < jTable1.getColumnCount(); columns++){
                        String value = jTable1.getModel().getValueAt(rows, columns).toString();
                        pdfTable.addCell(new Paragraph(value, arial));
                    }
                }
                
                PdfPTable pdfTable2 = new PdfPTable(jTable2.getColumnCount());
                
                for(int i = 0; i < jTable2.getColumnCount(); i++){
                    PdfPCell cell = new PdfPCell(new Paragraph(jTable2.getColumnName(i), arial));
                    pdfTable2.addCell(cell);
                }
                
                for (int rows = 0; rows < jTable2.getRowCount(); rows++){
                    for(int columns = 0; columns < jTable2.getColumnCount(); columns++){
                        String value = jTable2.getModel().getValueAt(rows, columns).toString();
                        pdfTable2.addCell(new Paragraph(value, arial));
                    }
                }
                
                
                
                //Προσθέτο στο pdf τα στοιχεία
                doc.add(new Paragraph("Προβολή στατιστικών σε PDF", arial18));
                doc.add(Chunk.NEWLINE);
                doc.add(pdfTable);
                doc.add(Chunk.NEWLINE);
                doc.add(pdfTable2);
                doc.close();
                
                //Άνοιγμα αρχείου κατευθείαν
                File myFile = new File("stats.pdf");
                Desktop.getDesktop().open(myFile);
                
            } catch (FileNotFoundException ex) {
                java.util.logging.Logger.getLogger(statisticsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (DocumentException ex) {
                java.util.logging.Logger.getLogger(statisticsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(statisticsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            
            
            
        }else{
            JOptionPane.showMessageDialog(null, "Παρακαλώ πατήστε πρώτα το κουμπί Προβολή");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(statisticsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(statisticsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(statisticsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(statisticsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new statisticsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
